#!/bin/bash

# Ablation Study Usage Guide
# This script provides interactive guidance for running ablation studies

echo "==============================================="
echo "🔬 PATCHXFORMER ABLATION STUDY USAGE GUIDE"
echo "==============================================="
echo ""

echo "Welcome! This guide will help you run PatchXFormer ablation studies."
echo ""

echo "📋 AVAILABLE ABLATION EXPERIMENTS:"
echo ""
echo "1. Quick Test (Recommended for first-time users)"
echo "   - Duration: ~30-60 minutes"
echo "   - Tests: 4 key model variants"
echo "   - Command: ./run_quick_ablation_test.sh"
echo ""

echo "2. Individual Component Tests"
echo "   - Test specific components individually"
echo "   - Duration: ~2-4 hours per script"
echo "   Commands:"
echo "   - ./run_patchxformer_full.sh                    # Full model"
echo "   - ./run_patchxformer_no_freq_attention.sh       # w/o frequency attention"
echo "   - ./run_patchxformer_no_enhanced_embedding.sh   # w/o enhanced embedding"
echo "   - ./run_patchxformer_no_adaptive_norm.sh        # w/o adaptive normalization"
echo "   - ./run_patchxformer_no_hybrid_encoder.sh       # w/o hybrid encoder"
echo "   - ./run_patchxformer_basic_patch.sh             # basic patch model"
echo ""

echo "3. Component Comparisons"
echo "   - Direct comparison between specific components"
echo "   - Duration: ~1-2 hours per comparison"
echo "   Commands:"
echo "   - ./run_component_comparison.sh attention       # Test frequency attention impact"
echo "   - ./run_component_comparison.sh embedding       # Test enhanced embedding impact"
echo "   - ./run_component_comparison.sh normalization   # Test adaptive norm impact"
echo "   - ./run_component_comparison.sh encoder         # Test hybrid encoder impact"
echo "   - ./run_component_comparison.sh all_vs_basic    # Full vs basic comparison"
echo ""

echo "4. Horizon-Specific Analysis"
echo "   - Test all models for specific forecast horizon"
echo "   - Duration: ~3-5 hours per horizon"
echo "   Commands:"
echo "   - ./run_single_horizon_ablation.sh 96          # 24-hour forecast"
echo "   - ./run_single_horizon_ablation.sh 192         # 48-hour forecast"
echo "   - ./run_single_horizon_ablation.sh 336         # 84-hour forecast"
echo "   - ./run_single_horizon_ablation.sh 720         # 180-hour forecast"
echo ""

echo "5. Complete Ablation Study"
echo "   - All models, all horizons"
echo "   - Duration: ~8-12 hours"
echo "   Commands:"
echo "   - ./run_all_ablation_scripts.sh full           # Master script"
echo "   - ./run_ablation_components.sh                 # Direct execution"
echo ""

echo "📊 RESULT ANALYSIS:"
echo ""
echo "After running experiments, analyze results with:"
echo "   python analyze_ablation_results.py"
echo ""
echo "This will generate:"
echo "   - ablation_study_analysis.png       # Visualization heatmaps"
echo "   - ablation_analysis_report.txt      # Detailed text report"
echo "   - ablation_detailed_results.csv     # Raw results data"
echo "   - ablation_component_impact.csv     # Impact analysis"
echo ""

echo "🎯 RECOMMENDATIONS:"
echo ""
echo "For beginners:"
echo "   1. ./run_quick_ablation_test.sh"
echo "   2. python analyze_ablation_results.py"
echo ""
echo "For thorough analysis:"
echo "   1. ./run_component_comparison.sh embedding      # Test highest impact component"
echo "   2. ./run_component_comparison.sh attention      # Test frequency attention"
echo "   3. python analyze_ablation_results.py"
echo ""
echo "For publication results:"
echo "   1. ./run_all_ablation_scripts.sh full"
echo "   2. python analyze_ablation_results.py"
echo ""

echo "💡 TIPS:"
echo ""
echo "- Start with quick test to verify everything works"
echo "- Monitor GPU memory usage during experiments"
echo "- Results are saved in ./results/ directory"
echo "- Check logs for any errors during execution"
echo "- Use screen/tmux for long-running experiments"
echo ""

echo "🔧 TROUBLESHOOTING:"
echo ""
echo "If you encounter errors:"
echo "   1. Check GPU availability: nvidia-smi"
echo "   2. Verify dataset path: ls ./dataset/sl_t/"
echo "   3. Test script syntax: bash test_script_syntax.sh"
echo "   4. Check Python dependencies: pip install -r requirements.txt"
echo ""

echo "==============================================="
echo "Ready to start ablation studies!"
echo "Choose an option above and run the corresponding command."
echo "==============================================="
